<a href="https://colab.research.google.com/github/FirstIntegral/PyTorch-DL/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00 PyTorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals

In [61]:
import torch
print(torch.__version__)

2.1.0+cu121


# Introcution to tensors

**Creating tensors**:
tensors in PyTorch are created using torch.tensor()

https://pytorch.org/docs/stable/tensors.html

In [62]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [63]:
scalar.ndim

0

has no dimensions, it's just a number

In [64]:
# get tensor back as a python int
scalar.item()

7

In [65]:
# vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [66]:
vector.ndim

1

In [67]:
vector.shape

torch.Size([2])

In [68]:
# MATRIX
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [69]:
MATRIX.ndim

2

In [70]:
MATRIX[0]

tensor([1, 2])

In [71]:
MATRIX.shape

torch.Size([2, 2])

In [72]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [73]:
TENSOR.ndim

3

In [74]:
TENSOR.shape

torch.Size([1, 3, 3])

In [75]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors
The way neural networks works is they start with tensors full of random numbers and adjust those numbers to better represent the data

`start with random numbers ==> look at data ==> update randomn umbers ==> look at data ==> update random numbers`

In [76]:
# create a random tensor of size (3, 4)
# docs here:https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6867, 0.3571, 0.0939, 0.6666],
        [0.9985, 0.1619, 0.7652, 0.6303],
        [0.5612, 0.8338, 0.5918, 0.7064]])

In [77]:
random_tensor.ndim

2

In [78]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # (height, width, color_channels) ==> (red, green, blue)
random_image_size_tensor

tensor([[[0.5705, 0.2448, 0.3969],
         [0.9724, 0.1045, 0.2689],
         [0.6018, 0.9164, 0.8647],
         ...,
         [0.2217, 0.8135, 0.1329],
         [0.5598, 0.3101, 0.9244],
         [0.7234, 0.1736, 0.3637]],

        [[0.6804, 0.8198, 0.8640],
         [0.3550, 0.5964, 0.8520],
         [0.1833, 0.2204, 0.8919],
         ...,
         [0.1617, 0.5875, 0.9753],
         [0.1508, 0.7376, 0.6144],
         [0.5906, 0.2620, 0.6441]],

        [[0.7797, 0.4956, 0.4762],
         [0.2485, 0.5815, 0.0970],
         [0.7122, 0.2915, 0.6608],
         ...,
         [0.7275, 0.9964, 0.0403],
         [0.5821, 0.8814, 0.1273],
         [0.0959, 0.1444, 0.2352]],

        ...,

        [[0.3467, 0.8446, 0.3396],
         [0.4709, 0.2587, 0.0398],
         [0.1752, 0.7974, 0.5741],
         ...,
         [0.9116, 0.4097, 0.7399],
         [0.2184, 0.6369, 0.0457],
         [0.4508, 0.5703, 0.5675]],

        [[0.3625, 0.0105, 0.4961],
         [0.2648, 0.0238, 0.6392],
         [0.

In [79]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [80]:
# creating a tensor of zeroes
zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [81]:
zero_tensor.shape, zero_tensor.ndim

(torch.Size([3, 4]), 2)

In [82]:
# create a tensor of ones
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
ones_tensor.shape, ones_tensor.ndim

(torch.Size([3, 4]), 2)