<a href="https://colab.research.google.com/github/FirstIntegral/PyTorch-DL/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **00 PyTorch fundamentals**

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals

In [1]:
import torch
print(torch.__version__)

2.1.0+cu121


# Introcution to tensors

**Creating tensors**:
tensors in PyTorch are created using torch.tensor()

https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

has no dimensions, it's just a number

In [4]:
# get tensor back as a python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([1, 2])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### **Random tensors**
The way neural networks works is they start with tensors full of random numbers and adjust those numbers to better represent the data

`start with random numbers ==> look at data ==> update randomn umbers ==> look at data ==> update random numbers`

In [16]:
# create a random tensor of size (3, 4)
# docs here:https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1853, 0.0340, 0.5203, 0.7011],
        [0.8798, 0.4606, 0.8673, 0.4689],
        [0.6661, 0.0168, 0.0990, 0.0604]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # (height, width, color_channels). color_channels of 3 here correspond to (red, green, blue)
random_image_size_tensor

tensor([[[0.1061, 0.2299, 0.5900],
         [0.0449, 0.1970, 0.9163],
         [0.1195, 0.8436, 0.2808],
         ...,
         [0.8359, 0.8380, 0.2638],
         [0.5620, 0.3918, 0.6172],
         [0.7352, 0.2591, 0.4516]],

        [[0.9912, 0.1113, 0.4105],
         [0.1618, 0.7613, 0.4543],
         [0.3093, 0.0261, 0.9806],
         ...,
         [0.0618, 0.3258, 0.5883],
         [0.1468, 0.6192, 0.5019],
         [0.1306, 0.8438, 0.5625]],

        [[0.9787, 0.6090, 0.9457],
         [0.4028, 0.4294, 0.7158],
         [0.8669, 0.9390, 0.4641],
         ...,
         [0.7201, 0.5648, 0.9260],
         [0.8915, 0.0733, 0.1787],
         [0.1385, 0.7329, 0.0583]],

        ...,

        [[0.9936, 0.8094, 0.6790],
         [0.5537, 0.3769, 0.4308],
         [0.6951, 0.2488, 0.8047],
         ...,
         [0.5130, 0.8432, 0.9329],
         [0.7121, 0.2300, 0.6196],
         [0.2128, 0.1596, 0.2576]],

        [[0.3206, 0.0917, 0.0133],
         [0.5739, 0.8856, 0.3172],
         [0.

In [19]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### **Zeros and ones**

In [20]:
# creating a tensor of zeroes
zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero_tensor.shape, zero_tensor.ndim

(torch.Size([3, 4]), 2)

In [22]:
# create a tensor of ones
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones_tensor.shape, ones_tensor.ndim

(torch.Size([3, 4]), 2)

### **Create a range of tensors and tensors-like**

In [24]:
# using torch.arange()
# https://pytorch.org/docs/stable/generated/torch.arange.html

one_to_ten = torch.arange(1,11) # similar to torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **Tensor datatypes**

In [26]:
# float32 tensor
float32_tensor = torch.tensor([[1.0,2.0], [3.0,4.0]], dtype=torch.float32)
float32_tensor

# By default, a dtype of "None" will give you a tensor of float16 i.e. `float16_tensor = torch.tensor([[1.0,2.0], [3.0,4.0]], dtype=None)`

tensor([[1., 2.],
        [3., 4.]])

In [27]:
# converting types of a tensor
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)

### In general, you get 3 errors while dealing with PyTprch:



1.   different dtypes error
2.   different shapes error
3.   different device error

1,2 are clear. 3 is when you do computation on two tensors and one of them lives in `device="cuda"` which is on an AMD **GPU**, and the other tensor lives in **CPU**.



In [28]:
another_float32_tensor = torch.tensor([[5.0,6.0], [7.0,8.0]], dtype=torch.float32, device=None, requires_grad=False)
another_float32_tensor

tensor([[5., 6.],
        [7., 8.]])

### Getting infromation from already made tensors. Such as `dtype`, `shape` and `device`

**dtype:** tensor.dtype

**shape:** tensor.shape

**device:** tensor.device

In [29]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2543, 0.4237, 0.6113, 0.6377],
        [0.6780, 0.7334, 0.9935, 0.4720],
        [0.8752, 0.2021, 0.3469, 0.1241]])

In [30]:
print(f"some_tensor has the shape of: {some_tensor.shape}\n and a dtype of: {some_tensor.dtype}\n and live on '{some_tensor.device}'")

some_tensor has the shape of: torch.Size([3, 4])
 and a dtype of: torch.float32
 and live on 'cpu'


### **Tensor operations**

*   Addition
*   Subtraction
*   Division
*   Multiplication (element-wise)
*   Matrix multiplication


In [31]:
# Create a tensor
tensor = torch.tensor([1.0, 2.0, 3.0])
tensor

tensor([1., 2., 3.])

In [32]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10.0

tensor([11., 12., 13.])

In [33]:
# Subtraction
tensor - 10.0

tensor([-9., -8., -7.])

In [34]:
# Multiplication
tensor * 10.0

tensor([10., 20., 30.])

In [35]:
# Division
tensor / 10.0

tensor([0.1000, 0.2000, 0.3000])

There are also other ways to do above, using PyTorch built-in functions such as `torch.mul`, `torch.add` but stick to python operations if there's no specific need and it's straight forward. No need for complications and it's easier to read

In [36]:
# Above operations messes up the dtype, converting it back again to torch.float32 so we can use it down below
tensor = tensor.type(torch.float32)

### **Matrix multiplication**

There are two ways to perform matrix multiplication in neural networks & deep learning:

1.   Element-wise
2.   Matrix multiplication (dot product) **(the most common)**



In [37]:
# 1. Element-wise
tensor * tensor
tensor.dtype

torch.float32

In [38]:
# 2. dot product
another_tensor = torch.tensor([4.0, 5.0, 6.0])
torch.matmul(tensor, another_tensor)

tensor(32.)

### **Dimensions matter.**
You cannot multiply any two matrices of any shape together. For matrix multiplication to be possible, the number of columns in the first matrix must equal the number of rows in the second matrix.

*   **Possible:** Matrix A (2x3) and Matrix B (3x2)
*   **Not Possible:** Matrix C (4x2) and Matrix D (3x4)




In [39]:
# Possible
possible_operation = torch.matmul(torch.rand(2, 3), torch.rand(3, 1))
possible_operation

tensor([[0.8191],
        [1.0902]])

In [40]:
# Not Possible
error_operation = torch.matmul(torch.rand(2, 3), torch.rand(2, 3))
error_operation

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.matmul(tensor_A, tensor_B) # could also just use `torch.mm(tensor_A, tensor_B)` mm == matmul == matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

doesn't work..... need to fix the shape using a transpose

In [42]:
tensor_A.shape

torch.Size([3, 2])

In [43]:
tensor_B.shape

torch.Size([3, 2])

transposing tensor_B... to be of shape (2,3)

In [44]:
tensor_B = tensor_B.T
torch.mm(tensor_A, tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### **Finding min, max, sum, mean...etc. (tensor aggregations)**

In [53]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
# Finding min
torch.min(x) # x.min()

tensor(0)

In [55]:
# Finding max
torch.max(x) # x.max()

tensor(90)

In [57]:
# Finding mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

torch mean function doesn't work with long (int64) data types...

In [63]:
x = x.type(torch.float32)
x
# OR just directly do this if oyu don't want to change the original tensor:
# torch.mean(x.type(torch.float32))

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [64]:
torch.mean(x)

tensor(45.)

In [65]:
# Finding sum
torch.sum(x)

tensor(450.)