<a href="https://colab.research.google.com/github/FirstIntegral/PyTorch-DL/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **00 PyTorch fundamentals**

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals

In [1]:
import torch
print(torch.__version__)

2.1.0+cu121


# Introcution to tensors

**Creating tensors**:
tensors in PyTorch are created using torch.tensor()

https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

has no dimensions, it's just a number

In [4]:
# get tensor back as a python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([1, 2])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### **Random tensors**
The way neural networks works is they start with tensors full of random numbers and adjust those numbers to better represent the data

`start with random numbers ==> look at data ==> update randomn umbers ==> look at data ==> update random numbers`

In [16]:
# create a random tensor of size (3, 4)
# docs here:https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7738, 0.2890, 0.2243, 0.3929],
        [0.4661, 0.8824, 0.4357, 0.8424],
        [0.4574, 0.3961, 0.8428, 0.3046]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # (height, width, color_channels). color_channels of 3 here correspond to (red, green, blue)
random_image_size_tensor

tensor([[[0.6976, 0.5687, 0.7782],
         [0.8593, 0.8952, 0.7114],
         [0.6197, 0.6623, 0.3359],
         ...,
         [0.5197, 0.7515, 0.7859],
         [0.1495, 0.3868, 0.9529],
         [0.6235, 0.1868, 0.7868]],

        [[0.2909, 0.2127, 0.2600],
         [0.0986, 0.4539, 0.3760],
         [0.3741, 0.4774, 0.0773],
         ...,
         [0.4795, 0.3153, 0.0851],
         [0.1501, 0.2491, 0.3270],
         [0.6380, 0.3596, 0.5132]],

        [[0.8736, 0.8519, 0.2044],
         [0.2818, 0.4637, 0.1073],
         [0.9733, 0.6032, 0.3092],
         ...,
         [0.5321, 0.1011, 0.4144],
         [0.6840, 0.5535, 0.3506],
         [0.5585, 0.1590, 0.2136]],

        ...,

        [[0.7480, 0.2481, 0.7326],
         [0.4146, 0.0024, 0.2689],
         [0.3046, 0.3557, 0.2393],
         ...,
         [0.2222, 0.6801, 0.5754],
         [0.2981, 0.3165, 0.4379],
         [0.5022, 0.9368, 0.8277]],

        [[0.5132, 0.5888, 0.3853],
         [0.3433, 0.8243, 0.5646],
         [0.

In [19]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### **Zeros and ones**

In [20]:
# creating a tensor of zeroes
zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero_tensor.shape, zero_tensor.ndim

(torch.Size([3, 4]), 2)

In [22]:
# create a tensor of ones
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones_tensor.shape, ones_tensor.ndim

(torch.Size([3, 4]), 2)

### **Create a range of tensors and tensors-like**

In [24]:
# using torch.arange()
# https://pytorch.org/docs/stable/generated/torch.arange.html

one_to_ten = torch.arange(1,11) # similar to torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **Tensor datatypes**

In [26]:
# float32 tensor
float32_tensor = torch.tensor([[1.0,2.0], [3.0,4.0]], dtype=torch.float32)
float32_tensor

# By default, a dtype of "None" will give you a tensor of float16 i.e. `float32_tensor = torch.tensor([[1.0,2.0], [3.0,4.0]], dtype=None)`

tensor([[1., 2.],
        [3., 4.]])

### In general, you get 3 errors while dealing with PyTprch:



1.   different dtypes error
2.   different shapes error
3.   different device error

1,2 are clear. 3 is when ou do computation on two tensors and one of them lives in `device="cuda"` which is on an AMD GPU, and the other tensor lives in CPU.



In [27]:
float32_tensor_new = torch.tensor([[5.0,6.0], [7.0,8.0]], dtype=torch.float32, device=None, requires_grad=False)
float32_tensor_new

tensor([[5., 6.],
        [7., 8.]])